### ISSUE TITLE
Chapter 07 - Uncaught ReferenceError: Handlebars is not defined

### ISSUE THREAD

**Issue by reddhouse** [EthanRBrown/web-development-with-node-and-express#63] opened 2016-02-11 16:18 UTC
Hi Ethan. I can't get the nursery rhyme examples in Chapter 7 to work. Line 23 in nursery-rhyme.handlebars causes the error: Uncaught ReferenceError: Handlebars is not defined

Line 23:
var nurseryRhymeTemplate = Handlebars.compile($('#nurseryRhymeTemplate').html());

Any suggestions?

**Comment by EthanRBrown** [comment] 2016-02-11 16:55
Hi, Justin,

Are you making sure to include (on the front end) the Handlebars library?  If you look at the [nursery rhyme view in the repo](https://github.com/EthanRBrown/web-development-with-node-and-express/blob/1.5.1/ch07/views/nursery-rhyme.handlebars), you'll see that on line 2 that the Handlebars library is included via CDN:

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.3.0/handlebars.min.js"></script>
```

**Comment by reddhouse** [comment] 2016-02-11 17:00
Yes, I copied the entire nursery-rhyme.handlbars file verbatim from your repo.

**Comment by EthanRBrown** [comment] 2016-02-11 17:05
Hm, well, I just tested it and it's working fine.  Are you actually running `node meadowlark.js` and visiting http://localhost:3000/nursery-rhyme, or did you copy it into an HTML file to view without the server?  What OS are you on?

**Comment by EthanRBrown** [comment] 2016-02-11 17:13
I propped it up on a server so you can take a look at it:

http://104.131.135.52:3000/nursery-rhyme

I wouldn't trust that link to be around for more than 24 hours or so...that's just a dev server.

**Comment by reddhouse** [comment] 2016-02-11 17:15
Yes, I am running node meadowlark.js from the terminal, and I am on OS X 10.11.3 (15D21). Everything has been working well (minus the open issue with cross page testing & zombie) until chapter 7.

I never forked your repo but was rather manually typing the code, or copying/pasting from your files. So, there are areas where there might be difference because npm gave me newer versions in some cases. For instance, I noticed that express3-handlebars is now express-handlebars.

The only public repo I have in my github account is this meadowlark project if you're willing to take a look. I just pushed everything from my mac to there a few minutes ago. I will view your dev server now.

**Comment by EthanRBrown** [comment] 2016-02-11 17:20
I just downloaded your repo and tried it.  The problem is the `head` section is not getting rendered server-side.  If you look at the HTML source when you visit the browser, you'll see the `head` section as referenced in the view isn't being rendered.  I'm taking a look now.

**Comment by EthanRBrown** [comment] 2016-02-11 17:24
You are not pulling in `_sections.head` in your `views/layouts/main.handlebars` file.  In that file, right before the closing `</head>` tag, add the following:

```html
    {{{_sections.head}}}
</head>
```

That fixes it right up!

**Comment by reddhouse** [comment] 2016-02-11 17:33
Indeed, and now I see you mentioned that was necessary at around location 2670 (in the kindle version). Sorry about that. I really appreciate your help, and have thoroughly enjoyed the book so far.

**Comment by EthanRBrown** [comment] 2016-02-11 17:45
I'm glad you're enjoying the book!  I hope to get to a second edition in 2017...there's lots I'd like to update!

**Closed by EthanRBrown** 2016-02-11 17:45 UTC

**Comment by YuryBY** [comment] 2016-06-09 12:17
@EthanRBrown, sorry, didn't found your email, so adding question to the thread: 
we used handlebars.js with Handlebars.VERSION = "1.0.0-rc.3";
today I tried to update the .js to v4.0.0 (replaced the old one by  handlebars-v4.0.0.js) but get following error: Handlebars is not defined in var template = Handlebars.compile(content);
There is really no Handlebars var in the .js. What I did wrong? How can I use .compile now? Thanks.

**Comment by EthanRBrown** [comment] 2016-06-09 18:53
Hi, @YuryBY ; I have not been able to keep the content of that book up to date with the latest version of Handlebars.  According to the current documentation `.compile` is still available, so I'm not sure why you would be experiencing this.  I am planning on a new edition of the book within the coming year, but I'm afraid for now you'll have to dig in and figure out what the changes from the old to new version of Handlebars are.  If you post your repo, I can take a look, but I have limited time.

**Comment by YuryBY** [comment] 2016-06-10 15:04
@EthanRBrown , thanks for the reply. It was needed some changes in our configs since file name had been changed from handlebars.js to handlebars-v4.0.5.js.
